import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "reset-css";
import "@fontsource/ubuntu/400.css";
import "@fontsource/ubuntu/500.css";
import "@fontsource/ubuntu/700.css";
import "./styles/global.css";
import SideNav from "./ui/side-nav";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Multi Step Form",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-screen w-full justify-center items-center bg-[#bee2fd]">
          <div className="max-w-[940px] w-full h-[600px] flex items-start p-4 gap-24 bg-white rounded-[15px]">
            <div className="flex flex-col w-[274px] h-full px-8 py-10 rounded-[10px] bg-[#483EFF] bg-center bg-no-repeat bg-cover">
              <SideNav />
            </div>
            <div className="h-full py-14">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
